spring:
  dubbo:
    application:
      name: my-provider
    registry:
      address: zookeeper://192.168.99.100:2181
    protocol:
      name: dubbo
      port: 20881
    scan: com.codedocker.nodeDubboExample.demoProvider